# Generated by Django 3.0 on 2021-07-28 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Inquiry',
            fields=[
                ('visa', models.CharField(choices=[('Student Visa', 'Student Visa'), ('Work Visa', 'Work Visa'), ('PR Visa', 'PR Visa'), ('Dependent Visa', 'Dependent Visa')], default='', max_length=200)),
                ('inquiry_num', models.AutoField(primary_key=True, serialize=False)),
                ('inquiry_date', models.DateField(max_length=8)),
                ('full_name', models.CharField(max_length=100)),
                ('dob', models.DateField(max_length=8)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='-', max_length=200)),
                ('address', models.TextField()),
                ('mobile', models.CharField(max_length=10)),
                ('whatsapp', models.CharField(max_length=10)),
                ('pin', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('married', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='-', max_length=200)),
                ('HSC_INS', models.CharField(default='-', max_length=200)),
                ('HSC_YEAR', models.CharField(default='-', max_length=20)),
                ('HSC_GRADES', models.CharField(default='-', max_length=20)),
                ('HSC_BACK', models.CharField(default='-', max_length=20)),
                ('DIPLOMA_INS', models.CharField(default='-', max_length=200)),
                ('DIPLOMA_YEAR', models.CharField(default='-', max_length=20)),
                ('DIPLOMA_GRADES', models.CharField(default='-', max_length=20)),
                ('DIPLOMA_BACK', models.CharField(default='-', max_length=20)),
                ('NACHOLOR_INS', models.CharField(default='-', max_length=200)),
                ('NACHOLOR_YEAR', models.CharField(default='-', max_length=20)),
                ('NACHOLOR_GRADES', models.CharField(default='-', max_length=20)),
                ('NACHOLOR_BACK', models.CharField(default='-', max_length=20)),
                ('MASTER_INS', models.CharField(default='-', max_length=200)),
                ('MASTER_YEAR', models.CharField(default='-', max_length=20)),
                ('MASTER_GRADES', models.CharField(default='-', max_length=20)),
                ('MASTER_BACK', models.CharField(default='-', max_length=20)),
                ('jobExp', models.CharField(default='No Experienc', max_length=20)),
                ('IfExam', models.CharField(choices=[('IELTS', 'IELTS'), ('TOEFL', 'TOEFL'), ('PTE', 'PTE')], default='No Appeared', max_length=200)),
                ('L', models.CharField(default='-', max_length=10)),
                ('R', models.CharField(default='-', max_length=10)),
                ('W', models.CharField(default='-', max_length=10)),
                ('S', models.CharField(default='-', max_length=10)),
                ('ALL', models.CharField(default='-', max_length=20)),
                ('country', models.CharField(choices=[('AUSTRALIA', 'AUSTRALIA'), ('CANADA', 'CANADA'), ('UK', 'UK'), ('USA', 'USA'), ('OTHERS', 'OTHERS')], default='', max_length=200)),
                ('intake', models.CharField(default='-', max_length=20)),
                ('FieldOfStudy', models.CharField(default='-', max_length=20)),
                ('HavePassport', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='-', max_length=200)),
                ('RelativesIn', models.CharField(choices=[('AUSTRALIA', 'AUSTRALIA'), ('CANADA', 'CANADA'), ('UK', 'UK'), ('USA', 'USA'), ('OTHERS', 'OTHERS')], default='', max_length=200)),
                ('CRequired', models.CharField(choices=[('IELTS Academic', 'IELTS Academic'), ('IELTS Genaral', 'IELTS Genaral'), ('Spoken English', 'Spoken English'), ('PTE', 'PTE')], default='No Appeared', max_length=200)),
                ('reference', models.CharField(choices=[('Social Media', 'Social Media'), ('Google', 'Google'), ('News Paper', 'News Paper'), ('Others', 'Others')], default='', max_length=200)),
                ('brance', models.CharField(choices=[('Social Media', 'Social Media'), ('Google', 'Google'), ('News Paper', 'News Paper'), ('Others', 'Others')], default='', max_length=200)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminArea.Admin_Registration')),
            ],
        ),
    ]
