# Generated by Django 3.0 on 2021-07-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0002_student_inquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_inquiry',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='student_inquiry',
            name='IfMarried',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='student_inquiry',
            name='address',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='student_inquiry',
            name='email',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_inquiry',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='student_inquiry',
            name='mobile',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='student_inquiry',
            name='pin',
            field=models.CharField(default='-', max_length=10),
        ),
    ]
