# Generated by Django 3.0 on 2021-07-28 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminArea', '0003_auto_20210728_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_inquiry',
            old_name='NACHOLOR_BACK',
            new_name='BACHOLOR_BACK',
        ),
        migrations.RenameField(
            model_name='student_inquiry',
            old_name='NACHOLOR_GRADES',
            new_name='BACHOLOR_GRADES',
        ),
        migrations.RenameField(
            model_name='student_inquiry',
            old_name='NACHOLOR_INS',
            new_name='BACHOLOR_INS',
        ),
        migrations.RenameField(
            model_name='student_inquiry',
            old_name='NACHOLOR_YEAR',
            new_name='BACHOLOR_YEAR',
        ),
    ]
